environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"    
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - npm install
  - npm run test

# Make clone much faster
shallow_clone: true

# Disable Visual Studio build and deploy
build: off
deploy: off

# Cache node modules, and refresh if package.json changes
cache:
  - node_modules -> package.json
